---
- name: install nginx
  apt: pkg=nginx state=installed force=yes
  notify:
    - nginx-restart

- name: set default nginx conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root mode=0600
  notify:
    - nginx-restart

- name: remove ssl example
  file: path=/etc/nginx/conf.d/example_ssl.conf state=absent
  notify:
    - nginx-restart

- include: vhost.yml