---
- name: install samba
  apt: pkg=samba state=latest
  notify:
    - samba-restart

- name: add samba config
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf mode=0640
  notify:
    - samba-restart
